"""Add default value for created_at in orders

Revision ID: 2c5a33d2c9a4
Revises: b8a4fb2b8dab
Create Date: 2025-09-18 23:35:25.779983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5a33d2c9a4'
down_revision: Union[str, Sequence[str], None] = 'b8a4fb2b8dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
