"""Rename order columns

Revision ID: b8a4fb2b8dab
Revises: 
Create Date: 2025-09-18 23:27:44.445542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8a4fb2b8dab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customerName', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customerEmail', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'customer_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('orders', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('orders', sa.Column('customer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_column('orders', 'createdAt')
    op.drop_column('orders', 'customerEmail')
    op.drop_column('orders', 'customerName')
    # ### end Alembic commands ###
